# Generated by Django 4.2 on 2024-12-17 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("mission", "미션 마니또"),
                            ("goodjob", "칭찬 마니또"),
                            ("gift", "선물 마니또"),
                        ],
                        max_length=20,
                    ),
                ),
                ("appear_data", models.DateTimeField()),
                ("headcount", models.PositiveIntegerField(default=3)),
                ("image", models.ImageField(blank=True, null=True, upload_to="rooms/")),
            ],
        ),
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mission_type",
                    models.CharField(
                        choices=[
                            ("커피", "커피 사주기"),
                            ("칭찬", "칭찬 쪽지 몰래 두기"),
                            ("간식", "간식 선물 하기"),
                            ("책상", "책상 정리 해주기"),
                            ("도움", "소소한 도움 주기"),
                            ("초상화", "초상화 그려주기"),
                            ("손편지", "손편지 써주기"),
                            ("사진", "사진 찍기"),
                            ("삼행시", "3행시 짓기"),
                        ],
                        max_length=20,
                    ),
                ),
                ("custom_mission", models.TextField(blank=True, null=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missions",
                        to="rooms.room",
                    ),
                ),
            ],
        ),
    ]
